language: go

go_import_path: github.com/screwyprof/cafe

go:
  - 1.8.x
  - 1.9.x
  - tip

script:
  - ./tests.sh

before_install:
  - go get -t -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)